version: 2.1

executors:
  default:
    docker:
      - image: cimg/node:lts
    working_directory: ~/dorm-swap-shop

jobs:
  eas_build:
    executor: default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Login to Expo
          command: npx expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
      - run:
          name: Trigger build
          command: npx eas-cli build --platform android --non-interactive # production build
          no_output_timeout: 20m

  # eas_deploy:
  #   executor: default
  #   steps:
  #   - checkout
  #   - run:
  #         name: Install EAS CLI
  #         command: npm install -g eas-cli
  #     - run:
  #         name: Deploy to Expo
  #         command: eas deploy --profile m-shoul

workflows:
  build_app:
    jobs:
      - eas_build:
          filters:
            branches:
              only:
                - main
                - develop
                - production

      # -eas_deploy:
      #   requires:
      #     - eas_build        